import { pathToFileURL } from 'node:url'
import { UNIVERSE_V0 } from '../src/universe'
import { average, percentile, prestigeBand, summarizeDistribution, type SignedRecruitRecord } from './dynastyLongRunMetrics'
import { runDynastyCalibration, runLongRunCalibration, type LongRunCalibrationResult, type ProgramRosterTrace } from './inspectDynastyLongRun'

const SEEDS = ['dynasty-long-run-v0:seed-1', 'dynasty-long-run-v0:seed-2', 'dynasty-long-run-v0:seed-3'] as const
const programs = [...UNIVERSE_V0.programs].sort((a, b) => b.basePrestige - a.basePrestige || a.id.localeCompare(b.id))
const TOP3 = new Set<string>(programs.slice(0, 3).map((p) => p.id)); const ELITE46 = new Set<string>(programs.slice(3, 6).map((p) => p.id)); const ELITE = new Set<string>(programs.slice(0, 6).map((p) => p.id))
const f = (v: number, d = 2) => Number.isFinite(v) ? v.toFixed(d) : '—'; const rate = (n: number, d: number) => d ? n / d : Number.NaN; const pct = (v: number) => Number.isFinite(v) ? `${f(v * 100, 1)}%` : '—'
const top = (r: ProgramRosterTrace, n: number) => average([...r.players].sort((a, b) => b.overall - a.overall).slice(0, n).map((p) => p.overall))
const seasonsArg = process.argv.indexOf('--seasons'); const SEASONS = seasonsArg >= 0 ? Number(process.argv[seasonsArg + 1]) : 25; const START = Math.min(5, SEASONS)

interface ClassRow { seed: string; season: number; programId: string; prestige: number; recruits: SignedRecruitRecord[]; avg: number; top3: number }
function classes(result: LongRunCalibrationResult): ClassRow[] { return result.runs.flatMap((run) => { const rs = run.signedRecruits.filter((r) => r.targetSeasonNumber >= START && r.targetSeasonNumber <= SEASONS); const keys = new Set(rs.map((r) => `${r.targetSeasonNumber}|${r.programId}`)); return [...keys].map((key) => { const [season, programId] = key.split('|'); const recruits = rs.filter((r) => r.targetSeasonNumber === Number(season) && r.programId === programId); const ovrs = recruits.map((r) => r.overall).sort((a, b) => b - a); return { seed: run.seed, season: Number(season), programId: programId!, prestige: recruits[0]!.prestige, recruits, avg: average(ovrs), top3: average(ovrs.slice(0, 3)) } }) }) }

function collision(result: LongRunCalibrationResult) {
  const opportunities = result.runs.flatMap((run) => run.recruitingOpportunities.filter((r) => r.targetSeasonNumber >= START && r.targetSeasonNumber <= SEASONS && ELITE.has(r.programId)))
  const keys = new Set(opportunities.map((r) => `${r.targetSeasonNumber}|${r.programId}|${r.playerId}|${result.runs.findIndex((run) => run.recruitingOpportunities.includes(r))}`))
  const histories = [...keys].map((key) => { const [season, programId, playerId, index] = key.split('|'); return opportunities.filter((r) => r.targetSeasonNumber === Number(season) && r.programId === programId && r.playerId === playerId && result.runs[Number(index)]!.recruitingOpportunities.includes(r)) })
  const eligible = histories.filter((h) => h[0]!.projectedOpening)
  const recruitKeys = new Set(opportunities.map((r) => `${r.targetSeasonNumber}|${r.playerId}|${result.runs.findIndex((run) => run.recruitingOpportunities.includes(r))}`))
  const seriousCounts = [...recruitKeys].map((key) => { const [season, playerId, index] = key.split('|'); return new Set(opportunities.filter((r) => r.targetSeasonNumber === Number(season) && r.playerId === playerId && result.runs[Number(index)]!.recruitingOpportunities.includes(r) && r.serious).map((r) => r.programId)).size })
  const snapshots = opportunities.filter((r) => r.nationalRank <= 25)
  return { eligible: eligible.length, offered: eligible.filter((h) => h.some((r) => r.offered)).length, serious: eligible.filter((h) => h.some((r) => r.serious)).length, avgSerious: average(seriousCounts), multi: rate(seriousCounts.filter((n) => n >= 2).length, seriousCounts.length), extraSnapshots: new Set(snapshots.filter((r) => r.activeOffersAtPosition > r.remainingOpeningsAtPosition).map((r) => `${r.targetSeasonNumber}|${r.programId}|${r.position}|${r.period}`)).size, lateExtras: snapshots.filter((r) => r.period >= 8 && r.activeOffersAtPosition > r.remainingOpeningsAtPosition).length }
}

function recruiting(result: LongRunCalibrationResult, exceptionalCutoff: number) {
  const cs = classes(result); const allSigned = cs.flatMap((c) => c.recruits); const premium = (c: ClassRow) => c.recruits.filter((r) => r.nationalRank <= 25).length; const elite = cs.filter((c) => ELITE.has(c.programId)); const nonElite = cs.filter((c) => !ELITE.has(c.programId)); const years = [...new Set(cs.map((c) => `${c.seed}|${c.season}`))]
  const concentration = years.map((id) => cs.filter((c) => `${c.seed}|${c.season}` === id && ELITE.has(c.programId)).map(premium).sort((a, b) => b - a))
  return { eliteTop10: elite.reduce((s, c) => s + c.recruits.filter((r) => r.nationalRank <= 10).length, 0), eliteTop25: elite.reduce((s, c) => s + premium(c), 0), eliteStars: elite.reduce((s, c) => s + c.recruits.filter((r) => r.stars >= 4).length, 0), elite80: elite.reduce((s, c) => s + c.recruits.filter((r) => r.overall >= 80).length, 0), exceptionalElite: rate(elite.filter((c) => c.top3 >= exceptionalCutoff).length, elite.length), exceptionalNonElite: rate(nonElite.filter((c) => c.top3 >= exceptionalCutoff).length, nonElite.length), threePremium: rate(elite.filter((c) => premium(c) >= 3).length, elite.length), fourPremium: rate(elite.filter((c) => premium(c) >= 4).length, elite.length), best: average(concentration.map((v) => v[0]!)), bestTwo: average(concentration.map((v) => v[0]! + v[1]!)), bestThree: average(concentration.map((v) => v.slice(0, 3).reduce((a, b) => a + b, 0))), bandTop25: Object.fromEntries(['80–100', '60–79', '40–59', '1–39'].map((band) => [band, allSigned.filter((r) => prestigeBand(r.prestige) === band && r.nationalRank <= 25).length])), top3Ovr: average(cs.filter((c) => TOP3.has(c.programId)).map((c) => c.avg)), elite46Ovr: average(cs.filter((c) => ELITE46.has(c.programId)).map((c) => c.avg)) }
}

function strength(result: LongRunCalibrationResult) {
  const seasons = result.runs.flatMap((run) => Array.from({ length: SEASONS - START + 1 }, (_, i) => run.rosterTraces.filter((r) => r.seasonNumber === START + i)))
  const spreads = seasons.map((rows) => { const values = rows.map((r) => r.overall); const s = summarizeDistribution(values); const sorted = [...values].sort((a, b) => b - a); return { sd: s.standardDeviation, p: s.p90 - s.p10, t4b4: average(sorted.slice(0, 4)) - average(sorted.slice(-4)), max: s.maximum, high: values.filter((v) => v >= 85).length, top3: average(rows.map((r) => top(r, 3))), top5: average(rows.map((r) => top(r, 5))), top8: average(rows.map((r) => top(r, 8))), rot: average(rows.map((r) => r.rotationWeightedPlayerOverall)) } })
  const avg = (key: keyof typeof spreads[number]) => average(spreads.map((r) => r[key])); return { sd: avg('sd'), p: avg('p'), t4b4: avg('t4b4'), max: Math.max(...spreads.map((r) => r.max)), high: spreads.reduce((s, r) => s + r.high, 0), top3: avg('top3'), top5: avg('top5'), top8: avg('top8'), rot: avg('rot') }
}

function tournament(result: LongRunCalibrationResult) {
  const obs = result.runs.flatMap((r) => r.tournamentBalanceCandidate.filter((o) => o.seasonNumber >= START && o.seasonNumber <= SEASONS)); const spread = (rows: number[]) => summarizeDistribution(rows).standardDeviation
  const leagueSd = average(result.runs.flatMap((r) => Array.from({ length: SEASONS - START + 1 }, (_, i) => spread(r.rosterTraces.filter((x) => x.seasonNumber === START + i).map((x) => x.overall)))))
  const fieldSd = average(obs.map((o) => spread(o.field.map((r) => r.overall)))); const top8Sd = average(obs.map((o) => spread(o.field.filter((r) => r.seed <= 8).map((r) => r.overall)))); const within5 = average(obs.map((o) => { const mean = average(o.field.map((r) => r.overall)); return rate(o.field.filter((r) => Math.abs(r.overall - mean) <= 5).length, o.field.length) }))
  const round1 = obs.flatMap((o) => o.games.filter((g) => g.round === 'round-of-16')); const matchup = Object.fromEntries([1, 2, 3, 4, 5].map((high) => { const low = 17 - high; const rows = round1.filter((g) => [g.homeSeed, g.awaySeed].includes(high) && [g.homeSeed, g.awaySeed].includes(low)); return [`${high}-${low}`, { gap: percentile(rows.map((r) => r.overallDifference), .5), lowerStronger: rate(rows.filter((g) => (g.homeSeed === low ? g.homeOverall : g.awayOverall) > (g.homeSeed === high ? g.homeOverall : g.awayOverall)).length, rows.length), seedUpset: rate(rows.filter((g) => g.seedUpset).length, rows.length), strengthUpset: rate(rows.filter((g) => g.strengthUpset).length, rows.length) }] }))
  const champions = obs.map((o) => o.field.find((r) => r.programId === o.championProgramId)!); return { leagueSd, fieldSd, top8Sd, within5, matchup, strongestTitle: rate(champions.filter((r) => r.actualOvrRank === 1).length, champions.length), top4Title: rate(champions.filter((r) => r.actualOvrRank <= 4).length, champions.length), bottomHalfTitle: rate(champions.filter((r) => r.actualOvrRank >= 9).length, champions.length), deepTitle: rate(champions.filter((r) => r.seed >= 9).length, champions.length), unique: result.runs.map((r) => Object.keys(r.champions).length).join('/') }
}

function health(result: LongRunCalibrationResult) { return result.runs.reduce((sum, run) => sum + Object.values(run.health).reduce((a, b) => a + b, 0), 0) }
function row(label: string, control: string | number, candidate: string | number) { console.log(`${label.padEnd(34)} ${String(control).padStart(14)} ${String(candidate).padStart(14)}`) }

export function main(): void {
  const control = runLongRunCalibration({ seasonsPerSeed: SEASONS, seeds: SEEDS, auditLevel: 'light' }); const candidate: LongRunCalibrationResult = { seeds: SEEDS, seasonsPerSeed: SEASONS, runs: SEEDS.map((seed) => runDynastyCalibration(seed, SEASONS, 'light', true)) }
  const cutoff = percentile(classes(control).map((c) => c.top3), .9); const cCol = collision(control), xCol = collision(candidate); const cRec = recruiting(control, cutoff), xRec = recruiting(candidate, cutoff); const cStr = strength(control), xStr = strength(candidate); const cTour = tournament(control), xTour = tournament(candidate)
  console.log('COLLEGE HOOPS SIM — PAIRED EARLY CLOSE-PREMIUM SECOND OFFER CANDIDATE'); console.log(`Configuration: paired ${SEEDS.length} seeds × ${SEASONS} Seasons × LIGHT; mature S${START}–${SEASONS}; candidate active planning Periods 1–8 and collapsed by production utility before Period 9.`)
  console.log('\nCONTROL                              CONTROL      CANDIDATE')
  row('Eligible elite top-25 opps', cCol.eligible, xCol.eligible); row('Ever Offered', `${cCol.offered} (${pct(rate(cCol.offered, cCol.eligible))})`, `${xCol.offered} (${pct(rate(xCol.offered, xCol.eligible))})`); row('Ever serious', `${cCol.serious} (${pct(rate(cCol.serious, cCol.eligible))})`, `${xCol.serious} (${pct(rate(xCol.serious, xCol.eligible))})`); row('Avg serious elite / top-25', f(cCol.avgSerious), f(xCol.avgSerious)); row('Top-25 with 2+ serious elite', pct(cCol.multi), pct(xCol.multi)); row('Extra-offer snapshots', cCol.extraSnapshots, xCol.extraSnapshots); row('Illegal extras Period 8+', cCol.lateExtras, xCol.lateExtras)
  console.log('\nRECRUITING CONCENTRATION'); row('Elite top-10 signees', cRec.eliteTop10, xRec.eliteTop10); row('Elite top-25 signees', cRec.eliteTop25, xRec.eliteTop25); row('Elite 4★+ signees', cRec.eliteStars, xRec.eliteStars); row('Elite incoming 80+', cRec.elite80, xRec.elite80); row('Elite exceptional classes', pct(cRec.exceptionalElite), pct(xRec.exceptionalElite)); row('Elite classes with 3+ top-25', pct(cRec.threePremium), pct(xRec.threePremium)); row('Elite classes with 4+ top-25', pct(cRec.fourPremium), pct(xRec.fourPremium)); row('Best elite top-25 / year', f(cRec.best), f(xRec.best)); row('Best two elite / year', f(cRec.bestTwo), f(xRec.bestTwo)); row('Best three elite / year', f(cRec.bestThree), f(xRec.bestThree)); row('Top 3 class OVR', f(cRec.top3Ovr), f(xRec.top3Ovr)); row('Elite #4–6 class OVR', f(cRec.elite46Ovr), f(xRec.elite46Ovr)); for (const band of Object.keys(cRec.bandTop25)) row(`${band} Prestige top-25`, cRec.bandTop25[band], xRec.bandTop25[band]); row('Non-elite exceptional classes', pct(cRec.exceptionalNonElite), pct(xRec.exceptionalNonElite))
  console.log('\nMATURE ROSTER / STRENGTH'); for (const [label, key] of [['Top-3 roster OVR', 'top3'], ['Top-5 roster OVR', 'top5'], ['Top-8 roster OVR', 'top8'], ['Rotation-weighted OVR', 'rot'], ['Strength SD', 'sd'], ['Strength P90-P10', 'p'], ['Strength top4-bottom4', 't4b4']] as const) row(label, f(cStr[key]), f(xStr[key])); row('Maximum Strength', f(cStr.max), f(xStr.max)); row('85+ Team-Seasons', cStr.high, xStr.high)
  console.log('\nTOURNAMENT / CHAMPIONS'); row('League Strength SD', f(cTour.leagueSd), f(xTour.leagueSd)); row('Field Strength SD', f(cTour.fieldSd), f(xTour.fieldSd)); row('Top-8 seed Strength SD', f(cTour.top8Sd), f(xTour.top8Sd)); row('Field within ±5', pct(cTour.within5), pct(xTour.within5)); for (const match of Object.keys(cTour.matchup)) { const a = cTour.matchup[match]!, b = xTour.matchup[match]!; row(`${match} median gap`, f(a.gap), f(b.gap)); row(`${match} lower seed stronger`, pct(a.lowerStronger), pct(b.lowerStronger)); row(`${match} seed/Strength upset`, `${pct(a.seedUpset)}/${pct(a.strengthUpset)}`, `${pct(b.seedUpset)}/${pct(b.strengthUpset)}`) } row('Strongest field team title', pct(cTour.strongestTitle), pct(xTour.strongestTitle)); row('Top-4 Strength title', pct(cTour.top4Title), pct(xTour.top4Title)); row('Bottom-half Strength title', pct(cTour.bottomHalfTitle), pct(xTour.bottomHalfTitle)); row('Seeds 9–16 title', pct(cTour.deepTitle), pct(xTour.deepTitle)); row('Unique champions by seed', cTour.unique, xTour.unique)
  console.log('\nLEGALITY'); row('Aggregate health violations', health(control), health(candidate))
}
if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) main()
