import { calculateOverall,type ClassYear } from '../src/engine'
import { initializeUniverse,UNIVERSE_V0 } from '../src/universe'
import { average,correlation,percentile } from './dynastyLongRunMetrics'
import { collectEndogenousPotReference } from './inspectEndogenousPotReference'
import { generateS0PotCandidateA,S0_POT_CANDIDATE_A } from './s0PotCandidateA'

const YEARS=['FR','SO','JR','SR'] as const
type Row={id:string;name:string;position:string;programId:string;prestige:number;year:ClassYear;ovr:number;pot:number;legacy:number;seed:string}
const gap=(r:Row)=>r.pot-r.ovr, fixed=(n:number,d=2)=>n.toFixed(d), pct=(n:number,d:number)=>`${fixed(n/d*100)}%`
const avg=(r:Row[],f:(x:Row)=>number)=>average(r.map(f)); const rate=(r:Row[],f:(x:Row)=>boolean)=>`${r.filter(f).length} (${pct(r.filter(f).length,r.length)})`
const summary=(v:number[])=>({mean:average(v),med:percentile(v,.5),p75:percentile(v,.75),p90:percentile(v,.9),p95:percentile(v,.95),p99:percentile(v,.99),max:v.reduce((a,b)=>Math.max(a,b),-Infinity)})
const table=(h:string[],rows:(string|number)[][])=>{console.log(`| ${h.join(' | ')} |\n| ${h.map(()=>`---`).join(' | ')} |`);rows.forEach(r=>console.log(`| ${r.join(' | ')} |`))}
function collect(universes:number,root:string){const rows:Row[]=[];for(let i=0;i<universes;i++){const seed=`${root}:${i}`;const u=initializeUniverse(UNIVERSE_V0,seed);for(const {program,team} of u.programs)for(const p of team.roster){const ovr=calculateOverall(p);rows.push({id:p.id,name:`${p.firstName} ${p.lastName}`,position:p.position,programId:program.id,prestige:team.prestige,year:p.classYear,ovr,pot:generateS0PotCandidateA({overall:ovr,classYear:p.classYear,universeSeed:seed,programId:program.id,playerId:p.id}),legacy:p.potential,seed})}}return rows}
const band=(r:Row)=>r.ovr<65?'<65':r.ovr<75?'65–74':r.ovr<85?'75–84':r.ovr<90?'85–89':'90+'
const hrBand=(r:Row)=>gap(r)<=3?'0–3':gap(r)<=7?'4–7':gap(r)<=12?'8–12':gap(r)<=19?'13–19':'20+'
function example(rows:Row[],test:(r:Row)=>boolean){const a=rows.filter(test).sort((x,y)=>x.ovr-y.ovr||x.id.localeCompare(y.id));const r=a[Math.floor(a.length/2)];return r?`${r.name} ${r.programId} ${r.position} ${r.year} ${r.ovr}/${r.pot} HR${gap(r)}`:'none'}
export function runReport(){const universes=Number(process.env.UNIVERSES??1000),root=process.env.SEED??'s0-pot-candidate-a:v1';const all=collect(universes,root);const ref=collectEndogenousPotReference(Math.max(500,Math.floor(universes/2)),'endogenous-pot-reference:v1').stages
 console.log(`# S0 POT Candidate A\n${JSON.stringify(S0_POT_CANDIDATE_A)}\nUniverses ${universes}; players ${all.length}; reference ${ref[0]!.length}; seed ${root}`)
 console.log('\n## POT marginals');table(['Class','N','Mean/med/P75/P90/P95/P99/max','80+','85+','90+','95+','97+','99'],YEARS.map(y=>{const r=all.filter(x=>x.year===y),s=summary(r.map(x=>x.pot));return[y,r.length,`${fixed(s.mean)}/${s.med}/${s.p75}/${s.p90}/${s.p95}/${s.p99}/${s.max}`,...[80,85,90,95,97].map(t=>rate(r,x=>x.pot>=t)),rate(r,x=>x.pot===99)]}))
 console.log('\n## Headroom/correlation');table(['Class','Mean/med/P75/P90/P95/P99/max','0–3','4–7','8–12','13–19','20+','30+','OVR↔POT','OVR↔HR'],YEARS.map(y=>{const r=all.filter(x=>x.year===y),s=summary(r.map(gap));return[y,`${fixed(s.mean)}/${s.med}/${s.p75}/${s.p90}/${s.p95}/${s.p99}/${s.max}`,...['0–3','4–7','8–12','13–19','20+'].map(b=>rate(r,x=>hrBand(x)===b)),rate(r,x=>gap(x)>=30),fixed(correlation(r.map(x=>({first:x.ovr,second:x.pot}))),3),fixed(correlation(r.map(x=>({first:x.ovr,second:gap(x)}))),3)]}))
 console.log('\n## Conditional');for(const y of YEARS)table([`${y} OVR`,'N','POT mean/med','POT90/95/97/99','HR mean','HR13+','HR20+'],['<65','65–74','75–84','85–89','90+'].map(b=>{const r=all.filter(x=>x.year===y&&band(x)===b);return[b,r.length,`${fixed(avg(r,x=>x.pot))}/${percentile(r.map(x=>x.pot),.5)}`,[90,95,97].map(t=>pct(r.filter(x=>x.pot>=t).length,r.length)).join('/')+`/${pct(r.filter(x=>x.pot===99).length,r.length)}`,fixed(avg(r,gap)),pct(r.filter(x=>gap(x)>=13).length,r.length),pct(r.filter(x=>gap(x)>=20).length,r.length)]}))
 const profiles=[['<65/POT85+', (r:Row)=>r.ovr<65&&r.pot>=85],['<65/POT95+',(r:Row)=>r.ovr<65&&r.pot>=95],['65–74/POT90+',(r:Row)=>r.ovr>=65&&r.ovr<75&&r.pot>=90],['75–84/POT95+',(r:Row)=>r.ovr>=75&&r.ovr<85&&r.pot>=95],['85–89/POT95+',(r:Row)=>r.ovr>=85&&r.ovr<90&&r.pot>=95],['85–89/POT97+',(r:Row)=>r.ovr>=85&&r.ovr<90&&r.pot>=97],['90+/POT95+',(r:Row)=>r.ovr>=90&&r.pot>=95],['90+/POT97+',(r:Row)=>r.ovr>=90&&r.pot>=97],['90+/POT99',(r:Row)=>r.ovr>=90&&r.pot===99],['85+/HR≤3',(r:Row)=>r.ovr>=85&&gap(r)<=3],['90+/HR≤3',(r:Row)=>r.ovr>=90&&gap(r)<=3]] as const
 console.log('\n## Joint');table(['Profile',...YEARS],profiles.map(([n,t])=>[n,...YEARS.map(y=>rate(all.filter(x=>x.year===y),t))]))
 const mixes=[['Polished75+/≤3',(r:Row)=>r.ovr>=75&&gap(r)<=3],['Ready80+/4–7',(r:Row)=>r.ovr>=80&&gap(r)>=4&&gap(r)<=7],['Developmental8–12',(r:Row)=>gap(r)>=8&&gap(r)<=12],['Project13–19',(r:Row)=>gap(r)>=13&&gap(r)<=19],['Extreme20+',(r:Row)=>gap(r)>=20],['<75/13+',(r:Row)=>r.ovr<75&&gap(r)>=13],['75+/13+',(r:Row)=>r.ovr>=75&&gap(r)>=13]] as const
 console.log('\n## Mix');table(['Profile',...YEARS],mixes.map(([n,t])=>[n,...YEARS.map(y=>rate(all.filter(x=>x.year===y),t))]))
 console.log('\n## Upperclass tails');for(const y of ['JR','SR'] as const)for(const h of [8,13,20]){const base=all.filter(x=>x.year===y),r=base.filter(x=>gap(x)>=h);console.log(`${y} HR${h}+ ${rate(base,x=>gap(x)>=h)} OVR ${fixed(avg(r,x=>x.ovr))}/${percentile(r.map(x=>x.ovr),.5)} POT ${fixed(avg(r,x=>x.pot))}/${percentile(r.map(x=>x.pot),.5)} POT90/95/97/99 ${[90,95,97].map(t=>pct(r.filter(x=>x.pot>=t).length,r.length)).join('/')}/${pct(r.filter(x=>x.pot===99).length,r.length)}`)}
 console.log('\n## Elite ceilings');for(const t of [90,95,97,99])table([`POT${t}${t===99?'':'+'}`,'N/rate','OVR mean/med','HR mean/med','≤3','≤7','13+','20+'],YEARS.map(y=>{const base=all.filter(x=>x.year===y),r=base.filter(x=>t===99?x.pot===99:x.pot>=t);return[y,rate(base,x=>t===99?x.pot===99:x.pot>=t),`${fixed(avg(r,x=>x.ovr))}/${percentile(r.map(x=>x.ovr),.5)}`,`${fixed(avg(r,gap))}/${percentile(r.map(gap),.5)}`,...[3,7].map(h=>pct(r.filter(x=>gap(x)<=h).length,r.length)),... [13,20].map(h=>pct(r.filter(x=>gap(x)>=h).length,r.length))]}))
 const p99=all.filter(x=>x.pot===99),counts=[...new Set(all.map(x=>x.seed))].map(s=>p99.filter(x=>x.seed===s).length);console.log(`\n## 99 POT\n${p99.length}/${all.length} ${pct(p99.length,all.length)}; ${fixed(p99.length/universes)} per universe; zero/one/two/3+ ${[0,1,2].map(n=>pct(counts.filter(c=>c===n).length,counts.length)).join('/')} / ${pct(counts.filter(c=>c>=3).length,counts.length)}; class ${YEARS.map(y=>`${y} ${p99.filter(x=>x.year===y).length}`).join(' | ')}; OVR ${fixed(avg(p99,x=>x.ovr))}/${percentile(p99.map(x=>x.ovr),.5)}/${percentile(p99.map(x=>x.ovr),.9)} range ${Math.min(...p99.map(x=>x.ovr))}-${Math.max(...p99.map(x=>x.ovr))}; HR ${fixed(avg(p99,gap))}/${percentile(p99.map(gap),.5)}`)
 console.log('\n## Examples');for(const y of YEARS){const r=all.filter(x=>x.year===y);console.log(`${y}: polished ${example(r,x=>x.ovr>=85&&gap(x)<=3)} | runway ${example(r,x=>x.ovr>=80&&gap(x)>=4&&gap(x)<=12)} | project ${example(r,x=>x.ovr<75&&x.pot>=95)} | exceptional ${example(r,x=>x.pot>=97&&gap(x)>=8)}`)}
 const groups=[...new Set(all.map(x=>x.seed))].map(seed=>({seed,r:all.filter(x=>x.seed===seed&&x.year==='FR').sort((a,b)=>b.ovr-a.ovr||a.id.localeCompare(b.id))})).sort((a,b)=>average(a.r.slice(0,3).map(x=>x.ovr))-average(b.r.slice(0,3).map(x=>x.ovr)));console.log('\n## Freshmen to Know');for(const [label,g] of [['Ordinary',groups[0]!],['Typical',groups[Math.floor(groups.length/2)]!],['Strong',groups.at(-1)!]] as const)console.log(`${label} ${g.seed}: ${g.r.slice(0,3).map(x=>`${x.name} ${x.programId} ${x.position} ${x.ovr}/${x.pot}`).join(' | ')}`)
 console.log('\n## Compact endogenous');table(['Stage','POT mean/med/90+/95+/97+/99','HR mean/med/13+/20+','Corr'],ref.map((r,i)=>{const n=r.length;return[`+${i}`,`${fixed(average(r.map(x=>x.potential)))}/${percentile(r.map(x=>x.potential),.5)}/${pct(r.filter(x=>x.potential>=90).length,n)}/${pct(r.filter(x=>x.potential>=95).length,n)}/${pct(r.filter(x=>x.potential>=97).length,n)}/${pct(r.filter(x=>x.potential===99).length,n)}`,`${fixed(average(r.map(x=>x.potential-x.overall)))}/${percentile(r.map(x=>x.potential-x.overall),.5)}/${pct(r.filter(x=>x.potential-x.overall>=13).length,n)}/${pct(r.filter(x=>x.potential-x.overall>=20).length,n)}`,fixed(correlation(r.map(x=>({first:x.overall,second:x.potential}))),3)]}))
 console.log(`\nPreservation IDs ${new Set(all.map(x=>x.id)).size===all.length}; legal ${all.every(x=>x.pot>=x.ovr&&x.pot<=99)}; only POT diagnostic; legacy retained ${all.every(x=>x.legacy>=x.ovr)}`)
}
if(import.meta.url===`file://${process.argv[1]}`)runReport()
