import { calculateOverall, type ClassYear } from '../src/engine'
import { initializeUniverse, UNIVERSE_V0 } from '../src/universe'
import { average, correlation, percentile } from './dynastyLongRunMetrics'
import { A4_CALIBRATION, checkA4Feasibility, deriveA4FactorSet, deriveA4Target, expectedA4Marginal } from './deriveS0PotCandidateA4Factors'
import { collectEndogenousPotReference } from './inspectEndogenousPotReference'
import { generateS0PotCandidateA } from './s0PotCandidateA'
import { generateS0PotCandidateA2, realizedFraction } from './s0PotCandidateA2'
import { generateS0PotCandidateA3 } from './s0PotCandidateA3'
import { generateS0PotCandidateA4, S0_POT_CANDIDATE_A4 } from './s0PotCandidateA4'

const YEARS = ['FR', 'SO', 'JR', 'SR'] as const; const ARMS = ['legacy', 'a1', 'a2', 'a3', 'a4'] as const
type Arm = typeof ARMS[number]
type Row = { id: string; name: string; program: string; position: string; year: ClassYear; ovr: number; legacy: number; a1: number; a2: number; a3: number; a4: number; seed: string }
type Ref = { overall: number; potential: number }
const fixed = (value: number, digits = 2) => value.toFixed(digits); const pct = (count: number, total: number) => total ? `${fixed(count / total * 100)}%` : 'n/a'
const table = (headers: string[], rows: (string | number)[][]) => { console.log(`| ${headers.join(' | ')} |\n| ${headers.map(() => '---').join(' | ')} |`); rows.forEach((row) => console.log(`| ${row.join(' | ')} |`)) }
const pot = (row: Row, arm: Arm) => row[arm]; const gap = (row: Row, arm: Arm) => pot(row, arm) - row.ovr; const rf = (row: Row, arm: Arm) => realizedFraction(row.ovr, pot(row, arm))
const rate = (rows: Row[], test: (row: Row) => boolean) => `${rows.filter(test).length} (${pct(rows.filter(test).length, rows.length)})`
const summary = (values: number[]) => ({ mean: average(values), med: percentile(values, .5), p75: percentile(values, .75), p90: percentile(values, .9), p95: percentile(values, .95), p99: percentile(values, .99), max: Math.max(...values) })
const band = (overall: number) => overall < 65 ? '<65' : overall < 75 ? '65–74' : overall < 85 ? '75–84' : overall < 90 ? '85–89' : '90+'
const hrBand = (headroom: number) => headroom <= 3 ? '0–3' : headroom <= 7 ? '4–7' : headroom <= 12 ? '8–12' : headroom <= 19 ? '13–19' : '20+'
const targetTail = (target: readonly number[], threshold: number) => target.slice(threshold - 60).reduce((sum, value) => sum + value, 0)

function collect(universes: number, root: string) {
  const rows: Row[] = []
  for (let index = 0; index < universes; index += 1) { const seed = `${root}:${index}`; const universe = initializeUniverse(UNIVERSE_V0, seed); for (const { program, team } of universe.programs) for (const player of team.roster) {
    const ovr = calculateOverall(player); const input = { overall: ovr, classYear: player.classYear, universeSeed: seed, programId: program.id, playerId: player.id }
    rows.push({ id: player.id, name: `${player.firstName} ${player.lastName}`, program: program.id, position: player.position, year: player.classYear, ovr, legacy: player.potential, a1: generateS0PotCandidateA(input), a2: generateS0PotCandidateA2(input), a3: generateS0PotCandidateA3(input), a4: generateS0PotCandidateA4(input), seed })
  }} return rows
}
function marginal(label: string, rows: Row[], arm: Arm) { const values = rows.map((row) => pot(row, arm)); const s = summary(values); return [label, `${fixed(s.mean)}/${s.med}/${s.p75}/${s.p90}/${s.p95}/${s.p99}/${s.max}`, ...[80,85,90,95,97].map((threshold) => pct(values.filter((value) => value >= threshold).length, values.length)), pct(values.filter((value) => value === 99).length, values.length)] }
function refMarginal(label: string, rows: Ref[]) { const values = rows.map((row) => row.potential); const s = summary(values); return [label, `${fixed(s.mean)}/${s.med}/${s.p75}/${s.p90}/${s.p95}/${s.p99}/${s.max}`, ...[80,85,90,95,97].map((threshold) => pct(values.filter((value) => value >= threshold).length, values.length)), pct(values.filter((value) => value === 99).length, values.length)] }
function elite(label: string, rows: Row[], arm: Arm, threshold: number) { const selected = rows.filter((row) => pot(row, arm) >= threshold); const os = summary(selected.map((row) => row.ovr)); const hs = summary(selected.map((row) => gap(row, arm))); const rs = summary(selected.map((row) => rf(row, arm))); return [label, selected.length, `${fixed(os.mean)}/${os.med}`, `${fixed(hs.mean)}/${hs.med}`, ...[3,7].map((value) => pct(selected.filter((row) => gap(row, arm) <= value).length, selected.length)), ...[13,20].map((value) => pct(selected.filter((row) => gap(row, arm) >= value).length, selected.length)), `${fixed(rs.mean,3)}/${fixed(rs.med,3)}`] }
function refElite(label: string, rows: Ref[], threshold: number) { const selected = rows.filter((row) => row.potential >= threshold); const os = summary(selected.map((row) => row.overall)); const hs = summary(selected.map((row) => row.potential-row.overall)); const rs = summary(selected.map((row) => realizedFraction(row.overall,row.potential))); return [label, selected.length, `${fixed(os.mean)}/${os.med}`, `${fixed(hs.mean)}/${hs.med}`, ...[3,7].map((value) => pct(selected.filter((row) => row.potential-row.overall <= value).length, selected.length)), ...[13,20].map((value) => pct(selected.filter((row) => row.potential-row.overall >= value).length, selected.length)), `${fixed(rs.mean,3)}/${fixed(rs.med,3)}`] }
function example(rows: Row[], test: (row: Row) => boolean) { const matches=rows.filter(test).sort((a,b)=>a.ovr-b.ovr||a.id.localeCompare(b.id)); return matches[Math.floor(matches.length/2)] }
function format(row?: Row) { return row ? `${row.name} | ${row.program} | ${row.position} | ${row.year} | ${row.ovr}/${row.a4} | HR${gap(row,'a4')} | r=${fixed(rf(row,'a4'),3)}` : 'none' }

export function runReport() {
  const universes = Number(process.env.UNIVERSES ?? 500); const root = process.env.SEED ?? 's0-pot-candidate-a4-holdout:v1'; const all = collect(universes,root)
  const { target, recruits } = deriveA4Target(); const primary = deriveA4FactorSet(A4_CALIBRATION.universes,A4_CALIBRATION.primarySeed,target); const robust = deriveA4FactorSet(A4_CALIBRATION.universes,A4_CALIBRATION.robustnessSeed,target); const references=collectEndogenousPotReference(500,'endogenous-pot-reference:v1').stages as Ref[][]
  console.log(`# S0 POT Candidate A4\n${JSON.stringify(S0_POT_CANDIDATE_A4)}\nHoldout ${universes} universes/${all.length} players seed ${root}; target ${recruits} recruits; reference ${references[0]!.length} careers`)
  console.log('\n## Target and calibration'); table(['Metric','Value'],[['Target mean',fixed(Array.from({length:40},(_,i)=>i+60).reduce((sum,value,index)=>sum+value*target[index]!,0),4)],...[80,85,90,95,97,99].map((threshold)=>[`Target ${threshold}${threshold===99?'':'+'}`,pct(targetTail(target,threshold),1)])])
  table(['Stage','N','Feasible/min slack@POT','Iterations','Max abs/rel error','Robust θ MAE/max@POT'],YEARS.map((year)=>{const counts=primary.histograms[year];const feasibility=checkA4Feasibility(counts,target);const solution=primary.solutions[year];const diffs=solution.theta.map((value,index)=>Math.abs(value-robust.solutions[year].theta[index]!));const worst=diffs.indexOf(Math.max(...diffs));return[year,counts.reduce((sum,value)=>sum+value,0),`${feasibility.feasible}/${fixed(feasibility.minimumSlack,8)}@${feasibility.threshold}`,solution.iterations,`${solution.maxAbsoluteError.toExponential(2)}/${solution.maxRelativeError.toExponential(2)}`,`${fixed(average(diffs),6)}/${fixed(diffs[worst]!,6)}@${worst+60}`]}))
  console.log('\n## Factor health');table(['Stage','factor min/med/max','θ min/med/max','max adjacent θ','75/80/85/90/95/97/98/99'],YEARS.map((year)=>{const theta=primary.solutions[year].theta;const factors=theta.map(Math.exp);const st=[...theta].sort((a,b)=>a-b),sf=[...factors].sort((a,b)=>a-b);return[year,`${fixed(sf[0]!,4)}/${fixed(sf[20]!,4)}/${fixed(sf.at(-1)!,4)}`,`${fixed(st[0]!,4)}/${fixed(st[20]!,4)}/${fixed(st.at(-1)!,4)}`,fixed(Math.max(...theta.slice(1).map((value,index)=>Math.abs(value-theta[index]!))),4),[75,80,85,90,95,97,98,99].map((p)=>fixed(Math.exp(theta[p-60]!),4)).join('/')]}))
  console.log('\n## Calibration expected vs target');table(['Stage','integer max/MAE','80+ Δ','85+ Δ','90+ Δ','95+ Δ','97+ Δ','99 Δ'],YEARS.map((year)=>{const m=expectedA4Marginal(primary.histograms[year],year,S0_POT_CANDIDATE_A4.theta[year]);const errors=m.map((value,index)=>Math.abs(value-target[index]!));return[year,`${Math.max(...errors).toExponential(2)}/${average(errors).toExponential(2)}`,...[80,85,90,95,97,99].map((threshold)=>fixed((targetTail(m,threshold)-targetTail(target,threshold))*100,5)+'pp')]}))
  console.log('\n## Holdout POT marginals');table(['Arm/stage','Mean/med/P75/P90/P95/P99/max','80+','85+','90+','95+','97+','99'],YEARS.flatMap((year,stage)=>{const rows=all.filter((row)=>row.year===year);return[marginal(`A1 ${year}`,rows,'a1'),marginal(`A2 ${year}`,rows,'a2'),marginal(`A3 ${year}`,rows,'a3'),marginal(`A4 ${year}`,rows,'a4'),refMarginal(`REF +${stage}`,references[stage]!)]}))
  console.log('\n## Holdout A4 error and class stability');table(['Stage','integer max/MAE','90+ Δ','95+ Δ','97+ Δ','99 Δ'],YEARS.map((year)=>{const rows=all.filter((row)=>row.year===year);const observed=Array.from({length:40},(_,index)=>rows.filter((row)=>row.a4===index+60).length/rows.length);const errors=observed.map((value,index)=>Math.abs(value-target[index]!));return[year,`${fixed(Math.max(...errors)*100,4)}pp/${fixed(average(errors)*100,4)}pp`,...[90,95,97,99].map((threshold)=>fixed((targetTail(observed,threshold)-targetTail(target,threshold))*100,3)+'pp')]}));for(const threshold of [95,97,99]){const fr=all.filter((row)=>row.year==='FR'&&(threshold===99?row.a4===99:row.a4>=threshold));const sr=all.filter((row)=>row.year==='SR'&&(threshold===99?row.a4===99:row.a4>=threshold));console.log(`${threshold}${threshold===99?'':'+'} FR/SR ratio ${fixed((fr.length/all.filter(r=>r.year==='FR').length)/(sr.length/all.filter(r=>r.year==='SR').length),3)}`)}
  console.log('\n## Elite count restoration');table(['Class/ceiling','A1','A3','A4','Target expected'],YEARS.flatMap((year)=>[95,97,99].map((threshold)=>{const rows=all.filter((row)=>row.year===year);const count=(arm:Arm)=>rows.filter((row)=>threshold===99?pot(row,arm)===99:pot(row,arm)>=threshold).length;return[`${year} ${threshold}${threshold===99?'':'+'}`,`${count('a1')}/${pct(count('a1'),rows.length)}`,`${count('a3')}/${pct(count('a3'),rows.length)}`,`${count('a4')}/${pct(count('a4'),rows.length)}`,`${fixed(rows.length*targetTail(target,threshold),1)}/${pct(targetTail(target,threshold),1)}`]})))
  console.log('\n## Elite carrier redistribution');for(const year of ['JR','SR'] as const)for(const threshold of [95,97]){const rowsOut=(['a1','a3','a4'] as const).map((arm)=>{const rows=all.filter((row)=>row.year===year&&pot(row,arm)>=threshold);return[arm.toUpperCase(),rows.length,...['<65','65–74','75–84','85–89','90+'].map((b)=>`${rows.filter((row)=>band(row.ovr)===b).length} (${pct(rows.filter((row)=>band(row.ovr)===b).length,rows.length)})`)]});const ref=references[YEARS.indexOf(year)]!.filter((row)=>row.potential>=threshold);rowsOut.push(['REF',ref.length,...['<65','65–74','75–84','85–89','90+'].map((b)=>`${ref.filter((row)=>band(row.overall)===b).length} (${pct(ref.filter((row)=>band(row.overall)===b).length,ref.length)})`)]);table([`${year} ${threshold}+`,'N','<65','65–74','75–84','85–89','90+'],rowsOut)}
  console.log('\n## Elite realization');for(const threshold of [95,97])table([`${threshold}+`,'N','OVR mean/med','HR mean/med','≤3','≤7','13+','20+','r mean/med'],(['JR','SR'] as const).flatMap((year)=>{const rows=all.filter((row)=>row.year===year),stage=YEARS.indexOf(year);return[elite(`A1 ${year}`,rows,'a1',threshold),elite(`A3 ${year}`,rows,'a3',threshold),elite(`A4 ${year}`,rows,'a4',threshold),refElite(`REF +${stage}`,references[stage]!,threshold)]}))
  console.log('\n## Headroom/correlation');table(['Stage','Mean/med','0–3','4–7','8–12','13–19','20+','8+','13+','20+','OVR↔POT','OVR↔HR'],YEARS.flatMap((year,stage)=>{const rows=all.filter((row)=>row.year===year),gaps=rows.map((row)=>gap(row,'a4')),ref=references[stage]!,rg=ref.map((row)=>row.potential-row.overall);return[[`A4 ${year}`,`${fixed(average(gaps))}/${percentile(gaps,.5)}`,...['0–3','4–7','8–12','13–19','20+'].map((b)=>pct(gaps.filter((g)=>hrBand(g)===b).length,gaps.length)),...[8,13,20].map((t)=>pct(gaps.filter((g)=>g>=t).length,gaps.length)),fixed(correlation(rows.map((row)=>({first:row.ovr,second:row.a4}))),3),fixed(correlation(rows.map((row)=>({first:row.ovr,second:gap(row,'a4')}))),3)],[`REF +${stage}`,`${fixed(average(rg))}/${percentile(rg,.5)}`,...['0–3','4–7','8–12','13–19','20+'].map((b)=>pct(rg.filter((g)=>hrBand(g)===b).length,rg.length)),...[8,13,20].map((t)=>pct(rg.filter((g)=>g>=t).length,rg.length)),fixed(correlation(ref.map((row)=>({first:row.overall,second:row.potential}))),3),fixed(correlation(ref.map((row)=>({first:row.overall,second:row.potential-row.overall}))),3)]]}))
  console.log('\n## Projects A4');const projects=[['<75/POT90+',(r:Row)=>r.ovr<75&&r.a4>=90],['<75/POT95+',(r:Row)=>r.ovr<75&&r.a4>=95],['<75/POT97+',(r:Row)=>r.ovr<75&&r.a4>=97],['<75/POT99',(r:Row)=>r.ovr<75&&r.a4===99],['<75/HR13+',(r:Row)=>r.ovr<75&&gap(r,'a4')>=13],['<75/HR20+',(r:Row)=>r.ovr<75&&gap(r,'a4')>=20]] as const;table(['Profile',...YEARS],projects.map(([label,test])=>[label,...YEARS.map((year)=>rate(all.filter((row)=>row.year===year),test))]))
  console.log('\n## High OVR A4');for(const year of YEARS)table([`${year} OVR`,'N','POT mean/med','95+','97+','99','≤3','≤7'],([['85–89',85,89],['90+',90,Infinity]] as const).map(([label,low,high])=>{const rows=all.filter((row)=>row.year===year&&row.ovr>=low&&row.ovr<=high);return[label,rows.length,`${fixed(average(rows.map(r=>r.a4)))}/${percentile(rows.map(r=>r.a4),.5)}`,...[95,97].map((t)=>pct(rows.filter(r=>r.a4>=t).length,rows.length)),pct(rows.filter(r=>r.a4===99).length,rows.length),...[3,7].map((h)=>pct(rows.filter(r=>gap(r,'a4')<=h).length,rows.length))]}))
  const p99=all.filter((row)=>row.a4===99),counts=[...new Set(all.map((row)=>row.seed))].map((seed)=>p99.filter((row)=>row.seed===seed).length);console.log(`\n## POT99\n${p99.length}/${all.length} ${pct(p99.length,all.length)}; ${fixed(p99.length/universes)} per universe; zero/one/two/3+ ${[0,1,2].map((n)=>pct(counts.filter(c=>c===n).length,counts.length)).join('/')} / ${pct(counts.filter(c=>c>=3).length,counts.length)}; OVR ${fixed(average(p99.map(r=>r.ovr)))}/${percentile(p99.map(r=>r.ovr),.5)} range ${Math.min(...p99.map(r=>r.ovr))}-${Math.max(...p99.map(r=>r.ovr))}; HR ${fixed(average(p99.map(r=>gap(r,'a4'))))}/${percentile(p99.map(r=>gap(r,'a4')),.5)}; r ${fixed(average(p99.map(r=>rf(r,'a4'))),3)}/${fixed(percentile(p99.map(r=>rf(r,'a4')),.5),3)}`);table(['Class','N/rate','OVR mean/med','HR mean/med'],YEARS.map((year)=>{const base=all.filter(r=>r.year===year),rows=p99.filter(r=>r.year===year);return[year,`${rows.length}/${pct(rows.length,base.length)}`,`${fixed(average(rows.map(r=>r.ovr)))}/${percentile(rows.map(r=>r.ovr),.5)}`,`${fixed(average(rows.map(r=>gap(r,'a4'))))}/${percentile(rows.map(r=>gap(r,'a4')),.5)}`]}))
  console.log('\n## Examples');for(const year of YEARS){const rows=all.filter(r=>r.year===year);console.log(`${year}\n  polished ${format(example(rows,r=>r.ovr>=85&&gap(r,'a4')<=3))}\n  runway ${format(example(rows,r=>r.ovr>=80&&gap(r,'a4')>=4&&gap(r,'a4')<=12))}\n  elite project ${format(example(rows,r=>r.ovr<75&&r.a4>=95))}\n  exceptional project ${format(example(rows,r=>r.ovr<75&&r.a4>=97))}`)}
  const groups=[...new Set(all.map(r=>r.seed))].map(seed=>({seed,rows:all.filter(r=>r.seed===seed&&r.year==='FR').sort((a,b)=>b.ovr-a.ovr||a.id.localeCompare(b.id))})).sort((a,b)=>average(a.rows.slice(0,3).map(r=>r.ovr))-average(b.rows.slice(0,3).map(r=>r.ovr)));console.log('\n## Freshmen to Know');for(const[label,g]of[['Ordinary',groups[0]!],['Typical',groups[Math.floor(groups.length/2)]!],['Strong',groups.at(-1)!]]as const)console.log(`${label} ${g.seed}: ${g.rows.slice(0,3).map(r=>`${r.name} ${r.program} ${r.position} ${r.ovr}/${r.a4}`).join(' | ')}`)
  console.log(`\n## Preservation\nPaired ${all.length}; all arms share non-POT inputs by construction; legal ${all.every(r=>ARMS.every(a=>pot(r,a)>=r.ovr&&pot(r,a)<=99))}; no runtime solve/counting; production POT retained; no production A4 import.`)
}
if(import.meta.url===`file://${process.argv[1]}`)runReport()
