import type { ProgramDefinition } from './domain'

export const UNIVERSE_V0_PROGRAMS = [
  {
    id: 'northbridge',
    name: 'Northbridge',
    abbreviation: 'NBR',
    conferenceId: 'atlantic-foundry',
    location: { city: 'Providence', stateCode: 'RI' },
    basePrestige: 88,
    branding: { primaryColor: '#6D4CC3', secondaryColor: '#C7CBD4' },
    identity:
      'Old northeastern private program with national expectations and a polished basketball tradition.',
  },
  {
    id: 'harbor-commonwealth',
    name: 'Harbor Commonwealth',
    abbreviation: 'HBR',
    conferenceId: 'atlantic-foundry',
    location: { city: 'Baltimore', stateCode: 'MD' },
    basePrestige: 80,
    branding: { primaryColor: '#159A9C', secondaryColor: '#D8B36A' },
    identity:
      'Big-city public institution whose deep local talent base keeps it nationally relevant.',
  },
  {
    id: 'capital-state',
    name: 'Capital State',
    abbreviation: 'CSU',
    conferenceId: 'atlantic-foundry',
    location: { city: 'Harrisburg', stateCode: 'PA' },
    basePrestige: 62,
    branding: { primaryColor: '#C23B3B', secondaryColor: '#F2E2C4' },
    identity: 'Steady state-capital program with loyal support and room to rise.',
  },
  {
    id: 'empire-polytechnic',
    name: 'Empire Polytechnic',
    abbreviation: 'EPI',
    conferenceId: 'atlantic-foundry',
    location: { city: 'Albany', stateCode: 'NY' },
    basePrestige: 73,
    branding: { primaryColor: '#3568D4', secondaryColor: '#C97A40' },
    identity:
      'Upstate technical institution pairing academic stature with sustained basketball ambition.',
  },
  {
    id: 'blue-ridge-state',
    name: 'Blue Ridge State',
    abbreviation: 'BRS',
    conferenceId: 'atlantic-foundry',
    location: { city: 'Roanoke', stateCode: 'VA' },
    basePrestige: 68,
    branding: { primaryColor: '#4B9AD9', secondaryColor: '#26313B' },
    identity: 'Regional public program that regularly competes above its resource level.',
  },
  {
    id: 'franklin-metro',
    name: 'Franklin Metro',
    abbreviation: 'FMU',
    conferenceId: 'atlantic-foundry',
    location: { city: 'Philadelphia', stateCode: 'PA' },
    basePrestige: 58,
    branding: { primaryColor: '#D86B2C', secondaryColor: '#34363A' },
    identity: 'Urban program attempting to establish itself in a crowded basketball market.',
  },
  {
    id: 'granite-coast',
    name: 'Granite Coast',
    abbreviation: 'GRC',
    conferenceId: 'atlantic-foundry',
    location: { city: 'Portsmouth', stateCode: 'NH' },
    basePrestige: 53,
    branding: { primaryColor: '#6F8194', secondaryColor: '#C5E3E8' },
    identity: 'Small northern institution with a devoted regional following and upset potential.',
  },
  {
    id: 'seaboard-university',
    name: 'Seaboard University',
    abbreviation: 'SBD',
    conferenceId: 'atlantic-foundry',
    location: { city: 'Wilmington', stateCode: 'DE' },
    basePrestige: 64,
    branding: { primaryColor: '#2D9D78', secondaryColor: '#173B57' },
    identity:
      'Mid-sized coastal university positioned between several eastern recruiting centers.',
  },
  {
    id: 'great-lakes',
    name: 'Great Lakes',
    abbreviation: 'GLU',
    conferenceId: 'lakes-union',
    location: { city: 'Detroit', stateCode: 'MI' },
    basePrestige: 91,
    branding: { primaryColor: '#2F9E6E', secondaryColor: '#0F3326' },
    identity: 'Flagship power with broad Midwestern reach and annual national expectations.',
  },
  {
    id: 'ironwood-state',
    name: 'Ironwood State',
    abbreviation: 'IWS',
    conferenceId: 'lakes-union',
    location: { city: 'Green Bay', stateCode: 'WI' },
    basePrestige: 83,
    branding: { primaryColor: '#3F7D55', secondaryColor: '#D1A43B' },
    identity:
      'Traditional northern contender with sustained success and strong regional loyalty.',
  },
  {
    id: 'lakefront-tech',
    name: 'Lakefront Tech',
    abbreviation: 'LFT',
    conferenceId: 'lakes-union',
    location: { city: 'Chicago', stateCode: 'IL' },
    basePrestige: 78,
    branding: { primaryColor: '#28A9C7', secondaryColor: '#152A3A' },
    identity: 'Urban technical program with growing resources and a high competitive ceiling.',
  },
  {
    id: 'midland-state',
    name: 'Midland State',
    abbreviation: 'MDS',
    conferenceId: 'lakes-union',
    location: { city: 'Grand Rapids', stateCode: 'MI' },
    basePrestige: 70,
    branding: { primaryColor: '#9E3F5B', secondaryColor: '#C6843D' },
    identity:
      'Dependable state program with strong local support and regular postseason ambitions.',
  },
  {
    id: 'prairie-junction',
    name: 'Prairie Junction',
    abbreviation: 'PJU',
    conferenceId: 'lakes-union',
    location: { city: 'Peoria', stateCode: 'IL' },
    basePrestige: 68,
    branding: { primaryColor: '#C89B2C', secondaryColor: '#202124' },
    identity: 'Central Illinois program built around regional continuity and steady competitiveness.',
  },
  {
    id: 'mill-city',
    name: 'Mill City',
    abbreviation: 'MCU',
    conferenceId: 'lakes-union',
    location: { city: 'Minneapolis', stateCode: 'MN' },
    basePrestige: 64,
    branding: { primaryColor: '#5557B9', secondaryColor: '#C77846' },
    identity: 'Metropolitan institution with a distinct civic profile and breakthrough potential.',
  },
  {
    id: 'riverbend-state',
    name: 'Riverbend State',
    abbreviation: 'RBS',
    conferenceId: 'lakes-union',
    location: { city: 'Davenport', stateCode: 'IA' },
    basePrestige: 60,
    branding: { primaryColor: '#4169B1', secondaryColor: '#D46A32' },
    identity:
      'Mississippi River regional program capable of assembling experienced, competitive rosters.',
  },
  {
    id: 'maumee-valley',
    name: 'Maumee Valley',
    abbreviation: 'MVU',
    conferenceId: 'lakes-union',
    location: { city: 'Toledo', stateCode: 'OH' },
    basePrestige: 52,
    branding: { primaryColor: '#8A5A3B', secondaryColor: '#D5B84A' },
    identity:
      'Smaller northwestern Ohio program seeking a path out of the conference’s lower tier.',
  },
  {
    id: 'appalachian-commonwealth',
    name: 'Appalachian Commonwealth',
    abbreviation: 'APC',
    conferenceId: 'southern-crescent',
    location: { city: 'Knoxville', stateCode: 'TN' },
    basePrestige: 82,
    branding: { primaryColor: '#2F6F5E', secondaryColor: '#C2B49A' },
    identity:
      'Historic mountain-region contender with strong support and consistent national relevance.',
  },
  {
    id: 'charlotte-tech',
    name: 'Charlotte Tech',
    abbreviation: 'CTU',
    conferenceId: 'southern-crescent',
    location: { city: 'Charlotte', stateCode: 'NC' },
    basePrestige: 76,
    branding: { primaryColor: '#3F7FE0', secondaryColor: '#17335C' },
    identity:
      'Emerging urban program with strong regional recruiting potential and rising expectations.',
  },
  {
    id: 'crescent-city',
    name: 'Crescent City',
    abbreviation: 'CRC',
    conferenceId: 'southern-crescent',
    location: { city: 'New Orleans', stateCode: 'LA' },
    basePrestige: 72,
    branding: { primaryColor: '#814D7A', secondaryColor: '#67BFA3' },
    identity:
      'Prominent urban institution with a distinctive identity and periodic national runs.',
  },
  {
    id: 'red-clay-state',
    name: 'Red Clay State',
    abbreviation: 'RCS',
    conferenceId: 'southern-crescent',
    location: { city: 'Montgomery', stateCode: 'AL' },
    basePrestige: 63,
    branding: { primaryColor: '#C45A3C', secondaryColor: '#E7D5B7' },
    identity:
      'Solid regional state program trying to turn local support into sustained success.',
  },
  {
    id: 'lowcountry-university',
    name: 'Lowcountry University',
    abbreviation: 'LCU',
    conferenceId: 'southern-crescent',
    location: { city: 'Charleston', stateCode: 'SC' },
    basePrestige: 59,
    branding: { primaryColor: '#D9765B', secondaryColor: '#1F4E4B' },
    identity: 'Coastal institution with an attractive setting and an uneven basketball history.',
  },
  {
    id: 'magnolia-am',
    name: 'Magnolia A&M',
    abbreviation: 'MAM',
    conferenceId: 'southern-crescent',
    location: { city: 'Jackson', stateCode: 'MS' },
    basePrestige: 55,
    branding: { primaryColor: '#7D3346', secondaryColor: '#C8BDB0' },
    identity:
      'Proud regional program searching for the resources to challenge the conference leaders.',
  },
  {
    id: 'coastal-plains',
    name: 'Coastal Plains',
    abbreviation: 'CPU',
    conferenceId: 'southern-crescent',
    location: { city: 'Savannah', stateCode: 'GA' },
    basePrestige: 46,
    branding: { primaryColor: '#2BA7A1', secondaryColor: '#0F3A38' },
    identity: 'Smaller coastal program offering a patient builder significant room for growth.',
  },
  {
    id: 'pine-valley',
    name: 'Pine Valley',
    abbreviation: 'PVA',
    conferenceId: 'southern-crescent',
    location: { city: 'Hattiesburg', stateCode: 'MS' },
    basePrestige: 36,
    branding: { primaryColor: '#B5842A', secondaryColor: '#40300F' },
    identity:
      'Resource-limited program that represents the universe’s clearest long-term rebuilding challenge.',
  },
  {
    id: 'golden-bay',
    name: 'Golden Bay',
    abbreviation: 'GBU',
    conferenceId: 'western-horizon',
    location: { city: 'Oakland', stateCode: 'CA' },
    basePrestige: 87,
    branding: { primaryColor: '#D4A72C', secondaryColor: '#493A72' },
    identity: 'West Coast power with major-market visibility and perennial national expectations.',
  },
  {
    id: 'summit-range',
    name: 'Summit Range',
    abbreviation: 'SMR',
    conferenceId: 'western-horizon',
    location: { city: 'Denver', stateCode: 'CO' },
    basePrestige: 79,
    branding: { primaryColor: '#B84B4B', secondaryColor: '#4F819D' },
    identity: 'High-altitude flagship with strong resources and consistent postseason ambition.',
  },
  {
    id: 'rainier-university',
    name: 'Rainier University',
    abbreviation: 'RNU',
    conferenceId: 'western-horizon',
    location: { city: 'Seattle', stateCode: 'WA' },
    basePrestige: 74,
    branding: { primaryColor: '#2E8B70', secondaryColor: '#B9DCE5' },
    identity:
      'Pacific Northwest institution with a growing profile and a broad regional draw.',
  },
  {
    id: 'mesa-vista',
    name: 'Mesa Vista',
    abbreviation: 'MVA',
    conferenceId: 'western-horizon',
    location: { city: 'Albuquerque', stateCode: 'NM' },
    basePrestige: 69,
    branding: { primaryColor: '#2C9C9A', secondaryColor: '#C86F48' },
    identity: 'Southwestern program with a distinctive regional identity and competitive stability.',
  },
  {
    id: 'sonoran-state',
    name: 'Sonoran State',
    abbreviation: 'SNS',
    conferenceId: 'western-horizon',
    location: { city: 'Tucson', stateCode: 'AZ' },
    basePrestige: 65,
    branding: { primaryColor: '#E08A2E', secondaryColor: '#27324A' },
    identity: 'Desert state program with reliable support and ambitions beyond the conference middle.',
  },
  {
    id: 'wasatch-college',
    name: 'Wasatch College',
    abbreviation: 'WSC',
    conferenceId: 'western-horizon',
    location: { city: 'Salt Lake City', stateCode: 'UT' },
    basePrestige: 58,
    branding: { primaryColor: '#315C89', secondaryColor: '#B8C2CC' },
    identity:
      'Mountain-region institution capable of occasional rises behind strong roster classes.',
  },
  {
    id: 'high-desert-state',
    name: 'High Desert State',
    abbreviation: 'HDU',
    conferenceId: 'western-horizon',
    location: { city: 'Boise', stateCode: 'ID' },
    basePrestige: 51,
    branding: { primaryColor: '#7C9A62', secondaryColor: '#252A26' },
    identity: 'Developing inland program still building a durable basketball identity.',
  },
  {
    id: 'mojave-tech',
    name: 'Mojave Tech',
    abbreviation: 'MVT',
    conferenceId: 'western-horizon',
    location: { city: 'Las Vegas', stateCode: 'NV' },
    basePrestige: 43,
    branding: { primaryColor: '#B54A7D', secondaryColor: '#D0A45A' },
    identity: 'Young technical institution with an unusual brand and substantial long-term upside.',
  },
] as const satisfies readonly ProgramDefinition[]
